### ISSUE TITLE
Website and releases are now offline

### ISSUE THREAD

**Issue by rsertelon** [SimonKagstrom/libghthash#1]
The upstream resource for `libghthash` known by everyone (it seems) is https://www.bth.se/people/ska/sim_home/libghthash.html Today it does not contain the releases/sources packages anymore, all seem to have disappeared (404).

This repository seems to contain the sources of this project (since you're the original author :)), although, there are no tags, so we can't really use it as a replacement to get a source package.

@SimonKagstrom is it possible for you to indicate if either:
* master will not move anymore and can be considered the last release then
* you're able to push tags to this git repository so we can use github's automatic archives to get source packages

Thanks!

> On a side note, the website is available in the wayback machine: https://web.archive.org/web/20170824230514/https://www.bth.se/people/ska/sim_home/libghthash.html

**Comment by SimonKagstrom** [comment]
Ah! It was quite a few years since I left BTH, so it's perhaps surprising that it was still around for so long.

I'll tag and release via github for now on, although as you see I don't work much on libghthash anymore :-).

I'll close this bug report once I've made the release.

**Comment by SimonKagstrom** [comment]
I've re-released 0.6.2 via a tag here, so closing this issue!

**Comment by rsertelon** [comment]
This is fantastic! Thanks a lot :) I'm a maintainer of a packaging system, and we had this package which wasn't building anymore, until now :) :tada:
